spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc123

  druid:
    aop-patterns: com.liuyang.*   #springbean监控
    filters: stat,wall,slf4j     #所有开启的功能

    stat-view-servlet:   #监控页配置
      enabled: true
      login-username: admin
      login-password: admin
      reset-enable: false

    web-stat-filter:   #web监控
      enabled: true
      url-pattern: /*
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


    filter:
      stat:  #sql监控
        slow-sql-millis: 1000
        log-slow-sql: true
        enabled: true
      wall:
        enabled: true

  jackson:
    # 格式化全局时间字段
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: GMT+8

#配置mybatis规则
mybatis:
#  mapper-locations: classpath:mapper/*.xml
  #忽视命名驼峰规则
  configuration:
    map-underscore-to-camel-case: true
    type-aliases-name: com.liuyang.bean

logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/blog.log

#开启sql日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

comment.avatar: /images/avatar.png
